#Chintan Patil - 21BCP284
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=Chintan$8113
ENV MYSQL_DATABASE=project

# Expose the MySQL port
EXPOSE 3308

# Define a named volume for MySQL data
VOLUME /var/lib/mysql

# Command to run the MySQL server
CMD ["mysqld"]

